{
  "cryptography":
  [
    {
      "description": "A flaw was found in the python-cryptography package. This issue may allow a remote attacker to decrypt captured messages in TLS servers that use RSA key exchanges, which may lead to exposure of confidential or sensitive data.",
      "vulnerability_id": "CVE-2023-50782",
      "name": "CVE-2023-50782",
      "package_name": "cryptography",
      "package_details":
      {
        "file_path": "opt/conda/lib/python3.9/site-packages/cryptography-41.0.7.dist-info/METADATA",
        "name": "cryptography",
        "package_manager": "PYTHONPKG",
        "version": "41.0.7",
        "release": null
      },
      "remediation":
      {
        "recommendation":
        {
          "text": "None Provided"
        }
      },
      "cvss_v3_score": 7.5,
      "cvss_v30_score": 0.0,
      "cvss_v31_score": 7.5,
      "cvss_v2_score": 0.0,
      "cvss_v3_severity": "HIGH",
      "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2023-50782",
      "source": "NVD",
      "severity": "HIGH",
      "status": "ACTIVE",
      "title": "CVE-2023-50782 - cryptography",
      "reason_to_ignore": "N/A"
    }
  ],
  "transformers":
  [
    {
      "description": "Deserialization of Untrusted Data in GitHub repository huggingface/transformers prior to 4.36.",
      "vulnerability_id": "CVE-2023-6730",
      "name": "CVE-2023-6730",
      "package_name": "transformers",
      "package_details":
      {
        "file_path": "opt/conda/lib/python3.9/site-packages/transformers-4.26.0.dist-info/METADATA",
        "name": "transformers",
        "package_manager": "PYTHONPKG",
        "version": "4.26.0",
        "release": null
      },
      "remediation":
      {
        "recommendation":
        {
          "text": "None Provided"
        }
      },
      "cvss_v3_score": 8.8,
      "cvss_v30_score": 0.0,
      "cvss_v31_score": 8.8,
      "cvss_v2_score": 0.0,
      "cvss_v3_severity": "HIGH",
      "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2023-6730",
      "source": "NVD",
      "severity": "HIGH",
      "status": "ACTIVE",
      "title": "CVE-2023-6730 - transformers",
      "reason_to_ignore": "N/A"
    },
    {
      "description": "Deserialization of Untrusted Data in GitHub repository huggingface/transformers prior to 4.36.",
      "vulnerability_id": "CVE-2023-7018",
      "name": "CVE-2023-7018",
      "package_name": "transformers",
      "package_details":
      {
        "file_path": "opt/conda/lib/python3.9/site-packages/transformers-4.26.0.dist-info/METADATA",
        "name": "transformers",
        "package_manager": "PYTHONPKG",
        "version": "4.26.0",
        "release": null
      },
      "remediation":
      {
        "recommendation":
        {
          "text": "None Provided"
        }
      },
      "cvss_v3_score": 7.8,
      "cvss_v30_score": 0.0,
      "cvss_v31_score": 7.8,
      "cvss_v2_score": 0.0,
      "cvss_v3_severity": "HIGH",
      "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2023-7018",
      "source": "NVD",
      "severity": "HIGH",
      "status": "ACTIVE",
      "title": "CVE-2023-7018 - transformers",
      "reason_to_ignore": "N/A"
    }
  ],
  "libzmq5":
  [
    {
      "reason_to_ignore": "The current version is marked as a fix version in the CVE notes, and this is the latest version.",
      "description": "\n It was discovered that ZeroMQ incorrectly handled certain application metadata.\n A remote attacker could use this issue to cause ZeroMQ to crash, or possibly\n execute arbitrary code.",
      "vulnerability_id": "CVE-2019-13132",
      "name": "CVE-2019-13132",
      "package_name": "libzmq5",
      "package_details":
      {
        "file_path": null,
        "name": "libzmq5",
        "package_manager": "OS",
        "version": "4.3.2",
        "release": "2ubuntu1"
      },
      "remediation":
      {
        "recommendation":
        {
          "text": "None Provided"
        }
      },
      "cvss_v3_score": 9.8,
      "cvss_v30_score": 0,
      "cvss_v31_score": 9.8,
      "cvss_v2_score": 7.5,
      "cvss_v3_severity": "CRITICAL",
      "source_url": "https://people.canonical.com/~ubuntu-security/cve/2019/CVE-2019-13132.html",
      "source": "UBUNTU_CVE",
      "severity": "HIGH",
      "status": "ACTIVE",
      "title": "CVE-2019-13132 - libzmq5"
    }
  ]
}