{
    "e2fsprogs": [
        {
            "description": " An out-of-bounds read/write vulnerability was found in e2fsprogs 1.46.5. This issue leads to a segmentation fault and possibly arbitrary code execution via a specially crafted filesystem.",
            "vulnerability_id": "CVE-2022-1304",
            "name": "CVE-2022-1304",
            "package_name": "e2fsprogs",
            "package_details": {
                "file_path": null,
                "name": "e2fsprogs",
                "package_manager": "OS",
                "version": "1.45.5",
                "release": "2ubuntu1"
            },
            "remediation": {
                "recommendation": {
                    "text": "None Provided"
                }
            },
            "cvss_v3_score": 7.8,
            "cvss_v30_score": 0.0,
            "cvss_v31_score": 7.8,
            "cvss_v2_score": 6.8,
            "cvss_v3_severity": "HIGH",
            "source_url": "https://people.canonical.com/~ubuntu-security/cve/2022/CVE-2022-1304.html",
            "source": "UBUNTU_CVE",
            "severity": "MEDIUM",
            "status": "ACTIVE",
            "title": "CVE-2022-1304 - e2fsprogs",
            "reason_to_ignore": "No newer version of e2fsprogs is available for Ubuntu 20.04 currently."
        }
    ],
    "cryptography": [
        {
            "description": " If an X.509 certificate contains a malformed policy constraint and policy processing is enabled, then a write lock will be taken twice recursively. On some operating systems (most widely: Windows) this results in a denial of service when the affected process hangs. Policy processing being enabled on a publicly facing server is not considered to be a common setup. Policy processing is enabled by passing the `-policy' argument to the command line utilities or by calling either `X509_VERIFY_PARAM_add0_policy()' or `X509_VERIFY_PARAM_set1_policies()' functions.",
            "vulnerability_id": "CVE-2022-3996",
            "name": "CVE-2022-3996",
            "package_name": "cryptography",
            "package_details": {
                "file_path": "usr/local/lib/python3.9/site-packages/cryptography-39.0.0.dist-info/METADATA",
                "name": "cryptography",
                "package_manager": "PYTHONPKG",
                "version": "39.0.0",
                "release": null
            },
            "remediation": {
                "recommendation": {
                    "text": "None Provided"
                }
            },
            "cvss_v3_score": 7.5,
            "cvss_v30_score": 0,
            "cvss_v31_score": 7.5,
            "cvss_v2_score": 0,
            "cvss_v3_severity": "HIGH",
            "source_url": "https://people.canonical.com/~ubuntu-security/cve/2022/CVE-2022-3996.html",
            "source": "UBUNTU_CVE",
            "severity": "LOW",
            "status": "ACTIVE",
            "title": "CVE-2022-3996 - cryptography"
        }
    ],
    "tensorflow-gpu": [
        {
            "description": "TensorFlow is an open source platform for machine learning. `tf.keras.losses.poisson` receives a `y_pred` and `y_true` that are passed through `functor::mul` in `BinaryOp`. If the resulting dimensions overflow an `int32`, TensorFlow will crash due to a size mismatch during broadcast assignment. We have patched the issue in GitHub commit c5b30379ba87cbe774b08ac50c1f6d36df4ebb7c. The fix will be included in TensorFlow 2.11. We will also cherrypick this commit on TensorFlow 2.10.1 and 2.9.3, as these are also affected and still in supported range. However, we will not cherrypick this commit into TensorFlow 2.8.x, as it depends on Eigen behavior that changed between 2.8 and 2.9.",
            "vulnerability_id": "CVE-2022-41887",
            "name": "CVE-2022-41887",
            "package_name": "tensorflow-gpu",
            "package_details": {
                "file_path": "usr/local/lib/python3.9/site-packages/tensorflow_gpu-2.8.4.dist-info/METADATA",
                "name": "tensorflow-gpu",
                "package_manager": "PYTHONPKG",
                "version": "2.8.4",
                "release": null
            },
            "remediation": {
                "recommendation": {
                    "text": "None Provided"
                }
            },
            "cvss_v3_score": 7.5,
            "cvss_v30_score": 0,
            "cvss_v31_score": 7.5,
            "cvss_v2_score": 0,
            "cvss_v3_severity": "HIGH",
            "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2022-41887",
            "source": "NVD",
            "severity": "HIGH",
            "status": "ACTIVE",
            "title": "CVE-2022-41887 - tensorflow-gpu",
            "reason_to_ignore": "TensorFlow 2.8.4 is the latest version of the framework version for this container."
        },
        {
            "description": "TensorFlow is an open source platform for machine learning. When ops that have specified input sizes receive a differing number of inputs, the executor will crash. We have patched the issue in GitHub commit f5381e0e10b5a61344109c1b7c174c68110f7629. The fix will be included in TensorFlow 2.11. We will also cherrypick this commit on TensorFlow 2.10.1, 2.9.3, and TensorFlow 2.8.4, as these are also affected and still in supported range.",
            "vulnerability_id": "CVE-2022-41883",
            "name": "CVE-2022-41883",
            "package_name": "tensorflow-gpu",
            "package_details": {
                "file_path": "usr/local/lib/python3.9/site-packages/tensorflow_gpu-2.8.4.dist-info/METADATA",
                "name": "tensorflow-gpu",
                "package_manager": "PYTHONPKG",
                "version": "2.8.4",
                "release": null
            },
            "remediation": {
                "recommendation": {
                    "text": "None Provided"
                }
            },
            "cvss_v3_score": 7.5,
            "cvss_v30_score": 0,
            "cvss_v31_score": 7.5,
            "cvss_v2_score": 0,
            "cvss_v3_severity": "HIGH",
            "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2022-41883",
            "source": "NVD",
            "severity": "HIGH",
            "status": "ACTIVE",
            "title": "CVE-2022-41883 - tensorflow-gpu"
        }
    ]

}
