{
  "mlflow": [
    {
      "description": "Deserialization of untrusted data can occur in versions of the MLflow platform running version 2.0.0rc0 or newer, enabling a maliciously uploaded Tensorflow model to run arbitrary code on an end user\u2019s system when interacted with.",
      "vulnerability_id": "CVE-2024-37057",
      "name": "CVE-2024-37057",
      "package_name": "mlflow",
      "package_details": {
        "file_path": "/opt/conda/lib/python3.11/site-packages/mlflow-2.18.0.dist-info/METADATA",
        "name": "mlflow",
        "package_manager": "PYTHON",
        "version": "2.18.0",
        "release": null
      },
      "remediation": { "recommendation": { "text": "None Provided" } },
      "cvss_v3_score": 8.8,
      "cvss_v30_score": 0.0,
      "cvss_v31_score": 8.8,
      "cvss_v2_score": 0.0,
      "cvss_v3_severity": "HIGH",
      "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-37057",
      "source": "NVD",
      "severity": "HIGH",
      "status": "ACTIVE",
      "title": "CVE-2024-37057 - mlflow",
      "reason_to_ignore": "N/A"
    },
    {
      "description": "Remote Code Execution can occur in versions of the MLflow platform running version 1.11.0 or newer, enabling a maliciously crafted MLproject to execute arbitrary code on an end user\u2019s system when run.",
      "vulnerability_id": "CVE-2024-37061",
      "name": "CVE-2024-37061",
      "package_name": "mlflow",
      "package_details": {
        "file_path": "/opt/conda/lib/python3.11/site-packages/mlflow-2.18.0.dist-info/METADATA",
        "name": "mlflow",
        "package_manager": "PYTHON",
        "version": "2.18.0",
        "release": null
      },
      "remediation": { "recommendation": { "text": "None Provided" } },
      "cvss_v3_score": 8.8,
      "cvss_v30_score": 0.0,
      "cvss_v31_score": 8.8,
      "cvss_v2_score": 0.0,
      "cvss_v3_severity": "HIGH",
      "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-37061",
      "source": "NVD",
      "severity": "HIGH",
      "status": "ACTIVE",
      "title": "CVE-2024-37061 - mlflow",
      "reason_to_ignore": "N/A"
    },
    {
      "description": "Deserialization of untrusted data can occur in versions of the MLflow platform running version 1.24.0 or newer, enabling a maliciously uploaded pmdarima model to run arbitrary code on an end user\u2019s system when interacted with.",
      "vulnerability_id": "CVE-2024-37055",
      "name": "CVE-2024-37055",
      "package_name": "mlflow",
      "package_details": {
        "file_path": "/opt/conda/lib/python3.11/site-packages/mlflow-2.18.0.dist-info/METADATA",
        "name": "mlflow",
        "package_manager": "PYTHON",
        "version": "2.18.0",
        "release": null
      },
      "remediation": { "recommendation": { "text": "None Provided" } },
      "cvss_v3_score": 8.8,
      "cvss_v30_score": 0.0,
      "cvss_v31_score": 8.8,
      "cvss_v2_score": 0.0,
      "cvss_v3_severity": "HIGH",
      "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-37055",
      "source": "NVD",
      "severity": "HIGH",
      "status": "ACTIVE",
      "title": "CVE-2024-37055 - mlflow",
      "reason_to_ignore": "N/A"
    },
    {
      "description": "Deserialization of untrusted data can occur in versions of the MLflow platform running version 1.23.0 or newer, enabling a maliciously uploaded LightGBM scikit-learn model to run arbitrary code on an end user\u2019s system when interacted with.",
      "vulnerability_id": "CVE-2024-37056",
      "name": "CVE-2024-37056",
      "package_name": "mlflow",
      "package_details": {
        "file_path": "/opt/conda/lib/python3.11/site-packages/mlflow-2.18.0.dist-info/METADATA",
        "name": "mlflow",
        "package_manager": "PYTHON",
        "version": "2.18.0",
        "release": null
      },
      "remediation": { "recommendation": { "text": "None Provided" } },
      "cvss_v3_score": 8.8,
      "cvss_v30_score": 0.0,
      "cvss_v31_score": 8.8,
      "cvss_v2_score": 0.0,
      "cvss_v3_severity": "HIGH",
      "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-37056",
      "source": "NVD",
      "severity": "HIGH",
      "status": "ACTIVE",
      "title": "CVE-2024-37056 - mlflow",
      "reason_to_ignore": "N/A"
    },
    {
      "description": "Deserialization of untrusted data can occur in versions of the MLflow platform running version 2.5.0 or newer, enabling a maliciously uploaded Langchain AgentExecutor model to run arbitrary code on an end user\u2019s system when interacted with.",
      "vulnerability_id": "CVE-2024-37058",
      "name": "CVE-2024-37058",
      "package_name": "mlflow",
      "package_details": {
        "file_path": "/opt/conda/lib/python3.11/site-packages/mlflow-2.18.0.dist-info/METADATA",
        "name": "mlflow",
        "package_manager": "PYTHON",
        "version": "2.18.0",
        "release": null
      },
      "remediation": { "recommendation": { "text": "None Provided" } },
      "cvss_v3_score": 8.8,
      "cvss_v30_score": 0.0,
      "cvss_v31_score": 8.8,
      "cvss_v2_score": 0.0,
      "cvss_v3_severity": "HIGH",
      "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-37058",
      "source": "NVD",
      "severity": "HIGH",
      "status": "ACTIVE",
      "title": "CVE-2024-37058 - mlflow",
      "reason_to_ignore": "N/A"
    },
    {
      "description": "A path traversal vulnerability exists in the mlflow/mlflow repository, specifically within the artifact deletion functionality. Attackers can bypass path validation by exploiting the double decoding process in the `_delete_artifact_mlflow_artifacts` handler and `local_file_uri_to_path` function, allowing for the deletion of arbitrary directories on the server's filesystem. This vulnerability is due to an extra unquote operation in the `delete_artifacts` function of `local_artifact_repo.py`, which fails to properly sanitize user-supplied paths. The issue is present up to version 2.9.2, despite attempts to fix a similar issue in CVE-2023-6831.",
      "vulnerability_id": "CVE-2024-1560",
      "name": "CVE-2024-1560",
      "package_name": "mlflow",
      "package_details": {
        "file_path": "/opt/conda/lib/python3.11/site-packages/mlflow-2.18.0.dist-info/METADATA",
        "name": "mlflow",
        "package_manager": "PYTHON",
        "version": "2.18.0",
        "release": null
      },
      "remediation": { "recommendation": { "text": "None Provided" } },
      "cvss_v3_score": 8.1,
      "cvss_v30_score": 0.0,
      "cvss_v31_score": 8.1,
      "cvss_v2_score": 0.0,
      "cvss_v3_severity": "HIGH",
      "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-1560",
      "source": "NVD",
      "severity": "HIGH",
      "status": "ACTIVE",
      "title": "CVE-2024-1560 - mlflow",
      "reason_to_ignore": "N/A"
    },
    {
      "description": "Deserialization of untrusted data can occur in versions of the MLflow platform running version 1.27.0 or newer, enabling a maliciously crafted Recipe to execute arbitrary code on an end user\u2019s system when run.",
      "vulnerability_id": "CVE-2024-37060",
      "name": "CVE-2024-37060",
      "package_name": "mlflow",
      "package_details": {
        "file_path": "/opt/conda/lib/python3.11/site-packages/mlflow-2.18.0.dist-info/METADATA",
        "name": "mlflow",
        "package_manager": "PYTHON",
        "version": "2.18.0",
        "release": null
      },
      "remediation": { "recommendation": { "text": "None Provided" } },
      "cvss_v3_score": 8.8,
      "cvss_v30_score": 0.0,
      "cvss_v31_score": 8.8,
      "cvss_v2_score": 0.0,
      "cvss_v3_severity": "HIGH",
      "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-37060",
      "source": "NVD",
      "severity": "HIGH",
      "status": "ACTIVE",
      "title": "CVE-2024-37060 - mlflow",
      "reason_to_ignore": "N/A"
    },
    {
      "description": "Deserialization of untrusted data can occur in versions of the MLflow platform running version 0.9.0 or newer, enabling a maliciously uploaded PyFunc model to run arbitrary code on an end user\u2019s system when interacted with.",
      "vulnerability_id": "CVE-2024-37054",
      "name": "CVE-2024-37054",
      "package_name": "mlflow",
      "package_details": {
        "file_path": "/opt/conda/lib/python3.11/site-packages/mlflow-2.18.0.dist-info/METADATA",
        "name": "mlflow",
        "package_manager": "PYTHON",
        "version": "2.18.0",
        "release": null
      },
      "remediation": { "recommendation": { "text": "None Provided" } },
      "cvss_v3_score": 8.8,
      "cvss_v30_score": 0.0,
      "cvss_v31_score": 8.8,
      "cvss_v2_score": 0.0,
      "cvss_v3_severity": "HIGH",
      "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-37054",
      "source": "NVD",
      "severity": "HIGH",
      "status": "ACTIVE",
      "title": "CVE-2024-37054 - mlflow",
      "reason_to_ignore": "N/A"
    },
    {
      "description": "Deserialization of untrusted data can occur in versions of the MLflow platform running version 1.1.0 or newer, enabling a maliciously uploaded scikit-learn model to run arbitrary code on an end user\u2019s system when interacted with.",
      "vulnerability_id": "CVE-2024-37052",
      "name": "CVE-2024-37052",
      "package_name": "mlflow",
      "package_details": {
        "file_path": "/opt/conda/lib/python3.11/site-packages/mlflow-2.18.0.dist-info/METADATA",
        "name": "mlflow",
        "package_manager": "PYTHON",
        "version": "2.18.0",
        "release": null
      },
      "remediation": { "recommendation": { "text": "None Provided" } },
      "cvss_v3_score": 8.8,
      "cvss_v30_score": 0.0,
      "cvss_v31_score": 8.8,
      "cvss_v2_score": 0.0,
      "cvss_v3_severity": "HIGH",
      "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-37052",
      "source": "NVD",
      "severity": "HIGH",
      "status": "ACTIVE",
      "title": "CVE-2024-37052 - mlflow",
      "reason_to_ignore": "N/A"
    },
    {
      "description": "Deserialization of untrusted data can occur in versions of the MLflow platform running version 0.5.0 or newer, enabling a maliciously uploaded PyTorch model to run arbitrary code on an end user\u2019s system when interacted with.",
      "vulnerability_id": "CVE-2024-37059",
      "name": "CVE-2024-37059",
      "package_name": "mlflow",
      "package_details": {
        "file_path": "/opt/conda/lib/python3.11/site-packages/mlflow-2.18.0.dist-info/METADATA",
        "name": "mlflow",
        "package_manager": "PYTHON",
        "version": "2.18.0",
        "release": null
      },
      "remediation": { "recommendation": { "text": "None Provided" } },
      "cvss_v3_score": 8.8,
      "cvss_v30_score": 0.0,
      "cvss_v31_score": 8.8,
      "cvss_v2_score": 0.0,
      "cvss_v3_severity": "HIGH",
      "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-37059",
      "source": "NVD",
      "severity": "HIGH",
      "status": "ACTIVE",
      "title": "CVE-2024-37059 - mlflow",
      "reason_to_ignore": "N/A"
    }
  ]
}
