{
  "torch": [
    {
      "reason_to_ignore": "The binaries are patched for this CVE, but the system checks version and not code.",
      "description": "[torch](https://pypi.org/project/torch) is a Tensors and Dynamic neural networks in Python with strong GPU acceleration\n\nAffected versions of this package are vulnerable to Command Injection in `torch.jit.annotations.parse_type_line` which can cause arbitrary code execution because `eval` is used unsafely.",
      "vulnerability_id": "SNYK-PYTHON-TORCH-3149871",
      "name": "SNYK-PYTHON-TORCH-3149871",
      "package_name": "torch",
      "package_details": {
        "file_path": "opt/conda/lib/python3.8/site-packages/torch-1.12.1+cpu.dist-info/METADATA",
        "name": "torch",
        "package_manager": "PYTHONPKG",
        "version": "1.12.1+cpu",
        "release": null
      },
      "remediation": { "recommendation": { "text": "None Provided" } },
      "cvss_v3_score": 9.8,
      "cvss_v30_score": 0.0,
      "cvss_v31_score": 9.8,
      "cvss_v2_score": 0.0,
      "cvss_v3_severity": "CRITICAL",
      "source_url": "https://snyk.io/vuln/SNYK-PYTHON-TORCH-3149871",
      "source": "SNYK",
      "severity": "CRITICAL",
      "status": "ACTIVE",
      "title": "IN1-PYTHON-TORCH-3149871 - torch"
    },
    {
      "reason_to_ignore": "The binaries are patched for this CVE, but the system checks version and not code.",  
      "description": " In PyTorch before trunk/89695, torch.jit.annotations.parse_type_line can cause arbitrary code execution because eval is used unsafely.",
      "vulnerability_id": "CVE-2022-45907",
      "name": "CVE-2022-45907",
      "package_name": "torch",
      "package_details": {
        "file_path": "opt/conda/lib/python3.8/site-packages/torch-1.12.1+cpu.dist-info/METADATA",
        "name": "torch",
        "package_manager": "PYTHONPKG",
        "version": "1.12.1+cpu",
        "release": null
      },
      "remediation": { "recommendation": { "text": "None Provided" } },
      "cvss_v3_score": 9.8,
      "cvss_v30_score": 0.0,
      "cvss_v31_score": 9.8,
      "cvss_v2_score": 0.0,
      "cvss_v3_severity": "CRITICAL",
      "source_url": "https://people.canonical.com/~ubuntu-security/cve/2022/CVE-2022-45907.html",
      "source": "UBUNTU_CVE",
      "severity": "MEDIUM",
      "status": "ACTIVE",
      "title": "CVE-2022-45907 - torch"
    }
  ],
  "libpython3.8": [
    {
      "reason_to_ignore": "Awaiting 3.8.16 for fix.",
      "description": " An issue was discovered in Python before 3.11.1. An unnecessary quadratic algorithm exists in one path when processing some inputs to the IDNA (RFC 3490) decoder, such that a crafted, unreasonably long name being presented to the decoder could lead to a CPU denial of service. Hostnames are often supplied by remote servers that could be controlled by a malicious actor; in such a scenario, they could trigger excessive CPU consumption on the client attempting to make use of an attacker-supplied supposed hostname. For example, the attack payload could be placed in the Location header of an HTTP response with status code 302. A fix is planned in 3.11.1, 3.10.9, 3.9.16, 3.8.16, and 3.7.16.",
      "vulnerability_id": "CVE-2022-45061",
      "name": "CVE-2022-45061",
      "package_name": "libpython3.8",
      "package_details": {
        "file_path": null,
        "name": "libpython3.8",
        "package_manager": "OS",
        "version": "3.8.10",
        "release": "0ubuntu1~20.04.5"
      },
      "remediation": { "recommendation": { "text": "None Provided" } },
      "cvss_v3_score": 7.5,
      "cvss_v30_score": 0.0,
      "cvss_v31_score": 7.5,
      "cvss_v2_score": 0.0,
      "cvss_v3_severity": "HIGH",
      "source_url": "https://people.canonical.com/~ubuntu-security/cve/2022/CVE-2022-45061.html",
      "source": "UBUNTU_CVE",
      "severity": "MEDIUM",
      "status": "ACTIVE",
      "title": "CVE-2022-45061 - python3.8, libpython3.8"
    },
    {
      "reason_to_ignore": "No Official resolution. Possible to have in 3.8.16",
      "description": " The Keccak XKCP SHA-3 reference implementation before fdc6fef has an integer overflow and resultant buffer overflow that allows attackers to execute arbitrary code or eliminate expected cryptographic properties. This occurs in the sponge function interface.",
      "vulnerability_id": "CVE-2022-37454",
      "name": "CVE-2022-37454",
      "package_name": "libpython3.8",
      "package_details": {
        "file_path": null,
        "name": "libpython3.8",
        "package_manager": "OS",
        "version": "3.8.10",
        "release": "0ubuntu1~20.04.5"
      },
      "remediation": { "recommendation": { "text": "None Provided" } },
      "cvss_v3_score": 9.8,
      "cvss_v30_score": 0.0,
      "cvss_v31_score": 9.8,
      "cvss_v2_score": 0.0,
      "cvss_v3_severity": "CRITICAL",
      "source_url": "https://people.canonical.com/~ubuntu-security/cve/2022/CVE-2022-37454.html",
      "source": "UBUNTU_CVE",
      "severity": "MEDIUM",
      "status": "ACTIVE",
      "title": "CVE-2022-37454 - python3.8, libpython3.8"
    }
  ],
  "python3.8": [
    {
      "reason_to_ignore": "Awaiting 3.8.16 for fix.",
      "description": " An issue was discovered in Python before 3.11.1. An unnecessary quadratic algorithm exists in one path when processing some inputs to the IDNA (RFC 3490) decoder, such that a crafted, unreasonably long name being presented to the decoder could lead to a CPU denial of service. Hostnames are often supplied by remote servers that could be controlled by a malicious actor; in such a scenario, they could trigger excessive CPU consumption on the client attempting to make use of an attacker-supplied supposed hostname. For example, the attack payload could be placed in the Location header of an HTTP response with status code 302. A fix is planned in 3.11.1, 3.10.9, 3.9.16, 3.8.16, and 3.7.16.",
      "vulnerability_id": "CVE-2022-45061",
      "name": "CVE-2022-45061",
      "package_name": "python3.8",
      "package_details": {
        "file_path": null,
        "name": "python3.8",
        "package_manager": "OS",
        "version": "3.8.10",
        "release": "0ubuntu1~20.04.5"
      },
      "remediation": { "recommendation": { "text": "None Provided" } },
      "cvss_v3_score": 7.5,
      "cvss_v30_score": 0.0,
      "cvss_v31_score": 7.5,
      "cvss_v2_score": 0.0,
      "cvss_v3_severity": "HIGH",
      "source_url": "https://people.canonical.com/~ubuntu-security/cve/2022/CVE-2022-45061.html",
      "source": "UBUNTU_CVE",
      "severity": "MEDIUM",
      "status": "ACTIVE",
      "title": "CVE-2022-45061 - python3.8, libpython3.8"
    },
    {
      "reason_to_ignore": "No Official resolution. Possible to have in 3.8.16",
      "description": " The Keccak XKCP SHA-3 reference implementation before fdc6fef has an integer overflow and resultant buffer overflow that allows attackers to execute arbitrary code or eliminate expected cryptographic properties. This occurs in the sponge function interface.",
      "vulnerability_id": "CVE-2022-37454",
      "name": "CVE-2022-37454",
      "package_name": "python3.8",
      "package_details": {
        "file_path": null,
        "name": "python3.8",
        "package_manager": "OS",
        "version": "3.8.10",
        "release": "0ubuntu1~20.04.5"
      },
      "remediation": { "recommendation": { "text": "None Provided" } },
      "cvss_v3_score": 9.8,
      "cvss_v30_score": 0.0,
      "cvss_v31_score": 9.8,
      "cvss_v2_score": 0.0,
      "cvss_v3_severity": "CRITICAL",
      "source_url": "https://people.canonical.com/~ubuntu-security/cve/2022/CVE-2022-37454.html",
      "source": "UBUNTU_CVE",
      "severity": "MEDIUM",
      "status": "ACTIVE",
      "title": "CVE-2022-37454 - python3.8, libpython3.8"
    }
  ]
}
